name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC 2019 environment
      uses: microsoft/setup-msbuild@v1

    - name: Build project
      run: |
        msbuild MK1Proxy.sln /p:Configuration=Release /p:Platform=x64
        cd MK160FPSPatch
        msbuild MK160FPSPatch.vcxproj /p:Configuration=Release /p:Platform=x64
      working-directory: ${{ github.workspace }}

    - name: Get version from .version file
      id: version
      # run: echo "version=$(cat .version)" >> $GITHUB_OUTPUT # Remove temporraily
      run: echo "version=Version123" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: MK160FPSPatch\x64\Release\dsound.dll
        name: Version ${{ steps.version.outputs.version }}
        tag_name:  v${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}

    # - name: Set release tag
    #   run: |
    #     git tag -a ${{ steps.version.outputs.version }} -m "Release v${{ steps.version.outputs.version }}"
    #     git push --follow-tags
